services:
  frontend:
    build: ./frontend
    volumes:
      - '/app/node_modules'
      - './frontend:/app'
    ports:
      - '9000:3000'
  backend:
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - '3000:9000'
    depends_on:
      - db
    build: ./server
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

